# Generated by Django 5.2.3 on 2025-06-19 08:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy summa')),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="Oldindan to'lov")),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Oylik to'lov")),
                ('duration_months', models.PositiveIntegerField(verbose_name='Muddati (oy)')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Yillik foiz stavkasi', max_digits=5, verbose_name='Foiz stavkasi (%)')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "To'lov rejasi",
                'verbose_name_plural': "To'lov rejalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('full', "To'liq to'lov"), ('partial', "Qisman to'lov"), ('prepayment', "Oldindan to'lov"), ('final', "Yakuniy to'lov"), ('refund', "Qaytarilgan to'lov")], max_length=20, verbose_name="To'lov turi")),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('transfer', "Bank o'tkazmasi"), ('online', "Online to'lov"), ('mobile', "Mobil to'lov"), ('installment', "Muddatli to'lov")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('scheduled_date', models.DateField(blank=True, help_text="Muddatli to'lovlar uchun", null=True, verbose_name='Rejalashtirilgan sana')),
                ('receipt_number', models.CharField(blank=True, help_text='Bank cheki yoki boshqa hujjat raqami', max_length=50, null=True, verbose_name='Chek/Hujjat raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Qaytarish sababi')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytarilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Buyurtma')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Qaytargan')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx')],
            },
        ),
    ]
