# Generated by Django 5.2.3 on 2025-06-19 08:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('advance', "Avans to'lov"), ('partial', "Qisman to'lov"), ('final', "Yakuniy to'lov")], default='partial', max_length=20, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="To'lov miqdori")),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'UzCard'), ('humo', 'Humo')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kvitansiya raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Buyurtma')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-payment_date'],
            },
        ),
    ]
