# Generated by Django 5.2.1 on 2025-06-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov miqdori")),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'UzCard'), ('humo', 'Humo')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Buyurtma')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-payment_date'],
            },
        ),
    ]
