# Generated by Django 5.2.3 on 2025-06-19 08:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kun")),
                ('phone', models.CharField(help_text='Asosiy aloqa telefon raqami', max_length=15, verbose_name='Asosiy telefon raqam')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Umumiy identifikator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('phone_type', models.CharField(choices=[('mobile', 'Mobil'), ('home', 'Uy'), ('work', 'Ish'), ('other', 'Boshqa')], default='mobile', max_length=10, verbose_name='Telefon turi')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy raqam')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='customers.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Telefon raqam',
                'verbose_name_plural': 'Telefon raqamlar',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('customer', 'phone')},
            },
        ),
    ]
