# Generated by Django 5.2.3 on 2025-06-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_telegram_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_telegra_389935_idx',
            old_name='customers_c_telegra_123456_idx',
        ),
    ]
