# Generated by Django 5.2.3 on 2025-07-12 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_c_telegra_123456_idx_customers_c_telegra_389935_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram bot orqali registratsiya qilingan foydalanuvchi ID', max_length=20, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['telegram_id'], name='customers_c_telegra_389935_idx'),
        ),
    ]
