# Generated by Django 5.2.3 on 2025-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_fathers_name_customer_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport raqami'),
        ),
    ]
