# Generated by Django 5.2.1 on 2025-06-03 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('measuring', "O'lchovda"), ('processing', 'Ishlanmoqda'), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat')),
                ('blind_type', models.CharField(choices=[('horizontal', 'Gorizontal jalyuzi'), ('vertical', 'Vertikal jalyuzi'), ('roller', 'Rulon parda'), ('roman', 'Rim parda'), ('plisse', 'Plisse parda')], max_length=30, verbose_name='Jalyuzi turi')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Eni (sm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Bo'yi (sm)")),
                ('material', models.CharField(choices=[('aluminum', 'Alyuminiy'), ('pvc', 'PVC'), ('wood', "Yog'och"), ('fabric', 'Mato'), ('bamboo', 'Bambuk')], max_length=20, verbose_name='Material turi')),
                ('installation_type', models.CharField(choices=[('wall', "Devorga o'rnatish"), ('ceiling', "Shiftga o'rnatish"), ('window_frame', "Deraza romiga o'rnatish")], max_length=30, verbose_name="O'rnatish turi")),
                ('mechanism_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mexanizm turi')),
                ('cornice_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Karniz turi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Donasi')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narxi')),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Oldindan to'lov")),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('measurement_date', models.DateField(blank=True, null=True, verbose_name="O'lchov sanasi")),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name="O'rnatish sanasi")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Mijoz')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
