# Generated by Django 5.2.3 on 2025-06-19 08:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('measuring', "O'lchovda"), ('processing', 'Ishlanmoqda'), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi')], default='measuring', max_length=20, verbose_name='Holat')),
                ('address', models.TextField(help_text="Jalyuzi o'rnatilishi kerak bo'lgan aniq manzil", verbose_name="O'lchov manzili")),
                ('latitude', models.FloatField(blank=True, help_text='GPS koordinata - kenglik', null=True, verbose_name='Kenglik (Latitude)')),
                ('longitude', models.FloatField(blank=True, help_text='GPS koordinata - uzunlik', null=True, verbose_name='Uzunlik (Longitude)')),
                ('location_accuracy', models.FloatField(blank=True, help_text='GPS aniqligi metrda', null=True, verbose_name='Joylashuv aniqligi (m)')),
                ('measurement_date', models.DateTimeField(blank=True, null=True, verbose_name="O'lchov sanasi")),
                ('measurement_notes', models.TextField(blank=True, null=True, verbose_name="O'lchov izohlari")),
                ('production_date', models.DateTimeField(blank=True, null=True, verbose_name='Ishlab chiqarish sanasi')),
                ('production_notes', models.TextField(blank=True, null=True, verbose_name='Ishlab chiqarish izohlari')),
                ('installation_date', models.DateTimeField(blank=True, null=True, verbose_name="O'rnatish sanasi")),
                ('installation_notes', models.TextField(blank=True, null=True, verbose_name="O'rnatish izohlari")),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Mijoz')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'rnatgan")),
                ('measured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'lchov olgan")),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ishlab chiqargan')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_type', models.CharField(choices=[('horizontal', 'Gorizontal'), ('vertical', 'Vertikal'), ('roller', 'Rulon'), ('roman', 'Rim'), ('pleated', 'Plisse'), ('wooden', "Yog'och"), ('aluminum', 'Alyuminiy')], max_length=20, verbose_name='Jalyuzi turi')),
                ('width', models.DecimalField(decimal_places=2, help_text='Santimetrda', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Eni (sm)')),
                ('height', models.DecimalField(decimal_places=2, help_text='Santimetrda', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Bo'yi (sm)")),
                ('material', models.CharField(choices=[('aluminum', 'Alyuminiy'), ('pvc', 'PVC'), ('wood', "Yog'och"), ('fabric', 'Mato'), ('bamboo', 'Bambuk'), ('metal', 'Metall')], max_length=20, verbose_name='Material turi')),
                ('installation_type', models.CharField(choices=[('ceiling', 'Shiftga'), ('wall', 'Devorga'), ('window_frame', 'Deraza romiga'), ('niche', 'Tokchaga')], max_length=20, verbose_name="O'rnatish turi")),
                ('mechanism', models.CharField(choices=[('cord', 'Ip bilan'), ('chain', 'Zanjir bilan'), ('motor', 'Elektr motor'), ('remote', 'Masofadan boshqarish'), ('manual', "Qo'lda")], default='cord', max_length=20, verbose_name='Mexanizm turi')),
                ('cornice_type', models.CharField(choices=[('standard', 'Standart'), ('decorative', 'Dekorativ'), ('hidden', 'Yashirin'), ('ceiling_mount', "Shiftga o'rnatilgan")], default='standard', max_length=20, verbose_name='Karniz turi')),
                ('room_name', models.CharField(blank=True, help_text='Masalan: Yotoq xona, Mehmonxona', max_length=100, null=True, verbose_name='Xona nomi')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rang')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Donasi')),
                ('unit_price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="1 kvadrat metr uchun narx so'mda", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birlik narxi (m² uchun)')),
                ('unit_price_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bir dona uchun umumiy narx', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Birlik narxi (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Yangi'), ('measuring', "O'lchovda"), ('processing', 'Ishlanmoqda'), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi')], max_length=20, null=True, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(choices=[('new', 'Yangi'), ('measuring', "O'lchovda"), ('processing', 'Ishlanmoqda'), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi')], max_length=20, verbose_name='Yangi holat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan vaqt")),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixlari',
                'ordering': ['-changed_at'],
            },
        ),
    ]
