# Generated by Django 5.2.3 on 2025-06-21 10:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('measuring', "O'lchovda"), ('processing', 'Ishlanmoqda'), ('installing', "O'rnatilmoqda"), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi')], default='measuring', max_length=20, verbose_name='Holat')),
                ('address', models.TextField(help_text="Jalyuzi o'rnatilishi kerak bo'lgan aniq manzil", verbose_name="O'lchov manzili")),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Umumiy narx')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="To'langan summa")),
                ('payment_status', models.CharField(choices=[('pending', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'liq to'langan"), ('overpaid', "Ortiqcha to'langan")], default='pending', max_length=20, verbose_name="To'lov holati")),
                ('measurement_date', models.DateTimeField(blank=True, null=True, verbose_name="O'lchov sanasi")),
                ('measurement_completed_date', models.DateTimeField(blank=True, null=True, verbose_name="O'lchov yakunlangan sana")),
                ('production_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Ishlab chiqarish boshlanish sanasi')),
                ('production_completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Ishlab chiqarish yakunlanish sanasi')),
                ('installation_completed_date', models.DateTimeField(blank=True, null=True, verbose_name="O'rnatish yakunlanish sanasi")),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('measurement_notes', models.TextField(blank=True, verbose_name="O'lchov ishi izohlari")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('assigned_installer', models.ForeignKey(blank=True, limit_choices_to={'can_install': True, 'role': 'technical'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installation_orders', to=settings.AUTH_USER_MODEL, verbose_name="Tayinlangan o'rnatuvchi")),
                ('assigned_manufacturer', models.ForeignKey(blank=True, limit_choices_to={'can_manufacture': True, 'role': 'technical'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manufacturing_orders', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlangan ishlab chiqaruvchi')),
                ('assigned_measurer', models.ForeignKey(blank=True, limit_choices_to={'can_measure': True, 'role': 'technical'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_measuring_orders', to=settings.AUTH_USER_MODEL, verbose_name="Tayinlangan o'lchov oluvchi")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_type', models.CharField(choices=[('horizontal', 'Gorizontal jalyuzi'), ('vertical', 'Vertikal jalyuzi'), ('roller', 'Rollo parda'), ('pleated', 'Plisse parda'), ('bamboo', 'Bambuk jalyuzi'), ('wooden', "Yog'och jalyuzi"), ('fabric', 'Mato jalyuzi')], max_length=20, verbose_name='Jalyuzi turi')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Eni (sm)')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name="Bo'yi (sm)")),
                ('material', models.CharField(choices=[('aluminum', 'Alyuminiy'), ('plastic', 'Plastik'), ('wood', "Yog'och"), ('fabric', 'Mato'), ('bamboo', 'Bambuk'), ('composite', 'Kompozit')], max_length=20, verbose_name='Material')),
                ('installation_type', models.CharField(choices=[('wall', "Devorga o'rnatish"), ('ceiling', "Shiftga o'rnatish"), ('window_frame', "Deraza romiga o'rnatish"), ('niche', "Ichki o'rnatish")], max_length=20, verbose_name="O'rnatish turi")),
                ('mechanism', models.CharField(choices=[('cord', 'Ip bilan boshqarish'), ('chain', 'Zanjir bilan boshqarish'), ('wand', 'Tayoqcha bilan boshqarish'), ('motorized', 'Elektr motor'), ('remote', 'Masofadan boshqarish'), ('smart', 'Aqlli boshqarish')], max_length=20, verbose_name='Mexanizm turi')),
                ('cornice_type', models.CharField(choices=[('standard', 'Standart karniz'), ('decorative', 'Dekorativ karniz'), ('hidden', 'Yashirin karniz'), ('box', 'Quti karniz'), ('double', 'Ikki qatorli karniz')], max_length=20, verbose_name='Karniz turi')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Donasi')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birlik narxi')),
                ('room_name', models.CharField(blank=True, max_length=100, verbose_name='Xona nomi')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izohlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'ordering': ['created_at'],
            },
        ),
    ]
