# Generated by Django 5.2.1 on 2025-06-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='blind_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cornice_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='installation_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mechanism_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_type', models.CharField(choices=[('horizontal', 'Gorizontal jalyuzi'), ('vertical', 'Vertikal jalyuzi'), ('roller', 'Rulon parda'), ('roman', 'Rim parda'), ('plisse', 'Plisse parda')], max_length=30, verbose_name='Jalyuzi turi')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Eni (sm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Bo'yi (sm)")),
                ('material', models.CharField(choices=[('aluminum', 'Alyuminiy'), ('pvc', 'PVC'), ('wood', "Yog'och"), ('fabric', 'Mato'), ('bamboo', 'Bambuk')], max_length=20, verbose_name='Material turi')),
                ('installation_type', models.CharField(choices=[('wall', "Devorga o'rnatish"), ('ceiling', "Shiftga o'rnatish"), ('window_frame', "Deraza romiga o'rnatish")], max_length=30, verbose_name="O'rnatish turi")),
                ('mechanism_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mexanizm turi')),
                ('cornice_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Karniz turi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Donasi')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narxi')),
                ('room_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xona nomi (masalan: Yotoq xona, Mehmonxona)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
    ]
