# Generated by Django 5.2.3 on 2025-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS koordinat - kenglik (-90 dan +90 gacha)', max_digits=10, null=True, verbose_name="O'lchov joyi kenglik (Latitude)"),
        ),
        migrations.AddField(
            model_name='order',
            name='measurement_location_accuracy',
            field=models.CharField(blank=True, help_text='GPS aniqlik darajasi (metrlarda)', max_length=50, verbose_name='GPS aniqlik'),
        ),
        migrations.AddField(
            model_name='order',
            name='measurement_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS koordinat - uzunlik (-180 dan +180 gacha)', max_digits=10, null=True, verbose_name="O'lchov joyi uzunlik (Longitude)"),
        ),
    ]
