# Generated by Django 5.2.1 on 2025-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_advance_payment_remove_order_blind_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Avans to'lovi"),
        ),
        migrations.AddField(
            model_name='order',
            name='advance_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Avans to'lovi sanasi"),
        ),
        migrations.AddField(
            model_name='order',
            name='advance_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'UzCard'), ('humo', 'Humo')], max_length=20, null=True, verbose_name="Avans to'lov usuli"),
        ),
    ]
