# Generated by Django 5.2.1 on 2025-06-03 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_advance_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='advance_payment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='advance_payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Bekor qilgan'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bekor qilingan sana'),
        ),
        migrations.AddField(
            model_name='order',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'rnatgan"),
        ),
        migrations.AddField(
            model_name='order',
            name='measured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'lchov olgan"),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ishlab chiqargan'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarish boshlangan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtmani qabul qilgan'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Buyurtma yaratildi'), ('status_changed', "Holat o'zgartirildi"), ('measured', "O'lchov olindi"), ('processing_started', 'Ishlab chiqarish boshlandi'), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi'), ('payment_received', "To'lov qabul qilindi"), ('updated', "Ma'lumotlar yangilandi")], max_length=20, verbose_name='Harakat')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Eski holat')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Yangi holat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Buyurtma')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma tarixi',
                'verbose_name_plural': 'Buyurtma tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
