# Generated by Django 5.2.3 on 2025-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_measurement_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan sana'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_notes',
            field=models.TextField(blank=True, verbose_name='Bekor qilingan izohlar'),
        ),
    ]
