# Generated by Django 5.2.2 on 2025-06-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_user_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='installed_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='measured_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processing_start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Aniqlanmagan manzil', help_text="Jalyuzi o'rnatilishi kerak bo'lgan aniq manzil", verbose_name="O'lchov manzili"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Avans to'lovi"),
        ),
        migrations.AddField(
            model_name='order',
            name='advance_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Avans to'lovi sanasi"),
        ),
        migrations.AddField(
            model_name='order',
            name='advance_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('bank_transfer', "Bank o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'UzCard'), ('humo', 'Humo')], max_length=20, null=True, verbose_name="Avans to'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('measuring', "O'lchovda"), ('processing', 'Ishlanmoqda'), ('installed', "O'rnatildi"), ('cancelled', 'Bekor qilindi')], default='measuring', max_length=20, verbose_name='Holat'),
        ),
    ]
