# Generated by Django 5.2.3 on 2025-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_date_order_cancelled_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installation_scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'rnatish sanasi"),
        ),
    ]
