# Generated by Django 5.2.2 on 2025-06-08 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_address_and_change_default_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Bekor qilgan'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bekor qilingan sana'),
        ),
        migrations.AddField(
            model_name='order',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'rnatgan"),
        ),
        migrations.AddField(
            model_name='order',
            name='measured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'lchov olgan"),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ishlab chiqargan'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarish boshlangan sana'),
        ),
    ]
