# Generated by Django 5.2.3 on 2025-07-21 11:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_installation_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Birlik narxi'),
        ),
    ]
