# Generated by Django 5.2.3 on 2025-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_paid_amount_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
