# Generated by Django 5.2.3 on 2025-07-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_active',
            new_name='is_measured',
        ),
    ]
